"""
Prompt construction for LLM-as-judge scoring of generated replies (Part 6).

Scores three dimensions independently rather than one blended "quality"
score, because a reply can be right on one axis and wrong on another
(e.g. perfectly on-tone but factually ungrounded) -- collapsing that into
one number hides exactly the failure modes worth finding.
"""

JUDGE_SYSTEM_PROMPT = """You are evaluating a DRAFT REPLY generated by an AI customer support \
agent for AmazonHelp, against the ORIGINAL customer message.

Score three dimensions, each 1-5 (5 = best):

1. relevance: does the reply actually address what the customer asked/complained about?
   1 = completely off-topic, 5 = directly addresses the core issue

2. correctness: does the reply avoid fabricating specifics (order numbers, dates, \
refund amounts, URLs, policy claims) not present in the customer's message or \
supported by real precedent? A safe, general reply that asks for more info via DM \
scores HIGH here even if it doesn't resolve the issue outright -- fabrication is \
the failure mode being measured, not lack of resolution.
   1 = invents specific false claims, 5 = makes no unsupported claims

3. tone: is the tone appropriate for a real brand support account -- empathetic, \
professional, not robotic, not dismissive?
   1 = tone-deaf or robotic, 5 = natural and appropriately empathetic

Respond with ONLY a JSON object:
{"relevance": <1-5>, "correctness": <1-5>, "tone": <1-5>, "rationale": "<one sentence>"}
No other text."""


def build_judge_prompt(customer_message: str, generated_reply: str, intent: str) -> str:
    return (
        f"Customer message:\n\"\"\"\n{customer_message}\n\"\"\"\n\n"
        f"Classified intent: {intent}\n\n"
        f"Draft reply to evaluate:\n\"\"\"\n{generated_reply}\n\"\"\"\n\n"
        f"Score this reply."
    )
